table DimAntigen

	column antigen_code
		dataType: string
		summarizeBy: none
		sourceColumn: antigen_code

		annotation SummarizationSetBy = Automatic

	column antigen_description
		dataType: string
		summarizeBy: none
		sourceColumn: antigen_description

		annotation SummarizationSetBy = Automatic

	partition DimAntigen = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(RepoRootPath & "\data\processed\clean_coverage.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"Antigen", "Antigen_description"}),
				    Deduped = Table.Distinct(Selected),
				    Typed = Table.TransformColumnTypes(Deduped, {{"Antigen", type text}, {"Antigen_description", type text}}),
				    Renamed = Table.RenameColumns(Typed, {{"Antigen", "antigen_code"}, {"Antigen_description", "antigen_description"}})
				in
				    Renamed

annotation PBI_ResultType = Table
