table DimDisease

	column disease_code
		dataType: string
		summarizeBy: none
		sourceColumn: disease_code

		annotation SummarizationSetBy = Automatic

	column disease_description
		dataType: string
		summarizeBy: none
		sourceColumn: disease_description

		annotation SummarizationSetBy = Automatic

	partition DimDisease = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(RepoRootPath & "\data\processed\clean_reported_cases.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(Promoted, {"Disease", "Disease_description"}),
				    Deduped = Table.Distinct(Selected),
				    Typed = Table.TransformColumnTypes(Deduped, {{"Disease", type text}, {"Disease_description", type text}}),
				    Renamed = Table.RenameColumns(Typed, {{"Disease", "disease_code"}, {"Disease_description", "disease_description"}})
				in
				    Renamed

annotation PBI_ResultType = Table
